name: Build Template

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: LemLib/pros-build@https://github.com/LemLib/Gamepad/actions/runs/9214344483/job/25350366702?pr=3
        with:
          library-path: gamepad
