name: Build Template

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: ABUCKY0/pros-build@e5b72507090341921a8194b4fadbe6dd5d1abd3c
        with:
          library-path: gamepad
