name: Build Template

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: ABUCKY0/pros-build@0cee92b2c04508f6b29bd02e8f6adfa31cdbc8f5
        with:
          library-path: gamepad
